# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cwf < Formula
  desc "Convoy Workflow tool: worktree/tmux session driver and turnkey sandboxing for the Convoy repos"
  homepage "https://github.com/convoyai/eng-dev-tooling"
  version "0.1.0"

  depends_on "git"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.0/cwf_0.1.0_darwin_amd64.tar.gz",
        headers: [
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "36828dc7ef0af578d2c2bbdea36ee8160e6b5a1ff57c05073968597e1be709e0"

      define_method(:install) do
        bin.install "cwf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.0/cwf_0.1.0_darwin_arm64.tar.gz",
        headers: [
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "fcd4d1129d244edc98d78b7521719edb7b1cf06cd4c621c39c5c47080096743b"

      define_method(:install) do
        bin.install "cwf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.0/cwf_0.1.0_linux_amd64.tar.gz",
        headers: [
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "9ec4f8223edabdc14a467edb01595b8b7ebaf10116a1b2b61e363cbd1207c52b"
      define_method(:install) do
        bin.install "cwf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.0/cwf_0.1.0_linux_arm64.tar.gz",
        headers: [
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "e616dd22e9298c856fd7594b956d207e1db0d78e1e90ec9eca3c27bd1a7d552a"
      define_method(:install) do
        bin.install "cwf"
      end
    end
  end

  def caveats
    <<~EOS
      cwf needs a sibling checkout of the eng-dev-tooling "Tools Repo" (the repo this
      formula is built from — it contains sandcat/profiles/ and the config schema) to
      resolve sandbox profiles and templates at runtime. See the Usage/Prerequisites
      section of that repo's README.md (and CONVOY-TOOL-DESIGN.md §9) for the
      sibling-checkout convention and the CONVOY_DEV_TOOLS override.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cwf version")
  end
end
