# This file was generated by GoReleaser. DO NOT EDIT.
cask "cwf" do
  require "download_strategy"
  require "json"

  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      set_github_token
      meta[:headers] ||= []
      meta[:headers] << "Accept: application/octet-stream"
      meta[:headers] << "Authorization: Bearer #{@github_token}"
      ghurl = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
      super(ghurl, name, version, **meta)
    end

    def parse_url_pattern
      url_pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid url pattern" unless @url =~ url_pattern

      _, @owner, @repo, @tag, @filename = *@url.match(url_pattern)
    end

    def download_url
      "https://#{@github_token}@api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
    end

    private

    def set_github_token
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      @github_token = github_cli_token if @github_token.to_s.empty?
      raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required." if @github_token.to_s.empty?

      ENV["HOMEBREW_GITHUB_API_TOKEN"] = @github_token

      # validate access
      GitHub.repository(@owner, @repo)
    end

    def github_cli_token
      gh = which("gh")
      if gh.nil?
        prefix_gh = HOMEBREW_PREFIX/"bin/gh"
        gh = prefix_gh if prefix_gh.executable?
      end
      return if gh.nil?

      raw = ::Utils.safe_popen_read(
        gh.to_s,
        "auth", "status",
        "--active",
        "--hostname", "github.com",
        "--json", "hosts",
        "--show-token",
      )
      parsed = JSON.parse(raw)
      return unless parsed.is_a?(Hash)

      hosts = parsed["hosts"]
      return unless hosts.is_a?(Hash)

      accounts = hosts["github.com"]
      return unless accounts.is_a?(Array)

      account = accounts.find do |candidate|
        candidate.is_a?(Hash) && candidate["active"] == true && candidate["state"] == "success"
      end
      return if account.nil?

      token = account["token"].to_s
      token unless token.empty?
    rescue ErrorDuringExecution, JSON::ParserError
      nil
    end

    def asset_id
      @asset_id ||= GitHub.get_release(@owner, @repo, @tag)["assets"]
                          .find { |a| a["name"] == @filename }
                          .fetch("id") { raise CurlDownloadStrategyError, "Asset not found" }
    end
  end

  version "0.13.2"

  on_macos do
    on_arm do
      sha256 "d22995ff90ad19a192aa79f8a07f8f86a29774a71bb062995fe16a55cf0cbe65"
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v#{version}/cwf_#{version}_darwin_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_intel do
      sha256 "ffbf118d23d5b68980330e164af5219ddb625db265c8ee14f61f38aa53dd6641"
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v#{version}/cwf_#{version}_darwin_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end
  on_linux do
    on_arm do
      sha256 "214687cea0b3e4d25497fa8241e530c7cfd801e7d92951d6871afacb70c84370"
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v#{version}/cwf_#{version}_linux_arm64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_intel do
      sha256 "6e4bafba1f6c3f583562cf7272da8d61b8d9bbc423797b4850810d4bc5dbc818"
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v#{version}/cwf_#{version}_linux_amd64.tar.gz",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "cwf"
  desc "Common Workflow tool: worktree/tmux session driver and turnkey sandboxing for the Common repos"
  homepage "https://github.com/convoyai/eng-dev-tooling"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "cwf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cwf"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    cwf needs a sibling checkout of the eng-dev-tooling "Tools Repo" (the repo this
    formula is built from — it contains the .cwf-tools-repo and sandcat/profiles/
    markers) to
    resolve sandbox profiles and templates at runtime. See the Usage/Prerequisites
    section of that repo's README.md (and docs/getting-started.md) for the
    sibling-checkout convention and the COMMON_DEV_TOOLS override.
  EOS
end
