# This file was generated by GoReleaser. DO NOT EDIT.
cask "cwf" do
  require "download_strategy"
  require "json"

  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      set_github_token
      meta[:headers] ||= []
      meta[:headers] << "Accept: application/octet-stream"
      meta[:headers] << "Authorization: Bearer #{@github_token}"
      ghurl = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
      super(ghurl, name, version, **meta)
    end

    def parse_url_pattern
      url_pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid url pattern" unless @url =~ url_pattern

      _, @owner, @repo, @tag, @filename = *@url.match(url_pattern)
    end

    def download_url
      "https://#{@github_token}@api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
    end

    private

    def set_github_token
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      @github_token = github_cli_token if @github_token.to_s.empty?
      raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required." if @github_token.to_s.empty?

      ENV["HOMEBREW_GITHUB_API_TOKEN"] = @github_token

      # validate access
      GitHub.repository(@owner, @repo)
    end

    def github_cli_token
      gh = which("gh")
      if gh.nil?
        prefix_gh = HOMEBREW_PREFIX/"bin/gh"
        gh = prefix_gh if prefix_gh.executable?
      end
      return if gh.nil?

      raw = ::Utils.safe_popen_read(
        gh.to_s,
        "auth", "status",
        "--active",
        "--hostname", "github.com",
        "--json", "hosts",
        "--show-token",
      )
      parsed = JSON.parse(raw)
      return unless parsed.is_a?(Hash)

      hosts = parsed["hosts"]
      return unless hosts.is_a?(Hash)

      accounts = hosts["github.com"]
      return unless accounts.is_a?(Array)

      account = accounts.find do |candidate|
        candidate.is_a?(Hash) && candidate["active"] == true && candidate["state"] == "success"
      end
      return if account.nil?

      token = account["token"].to_s
      token unless token.empty?
    rescue ErrorDuringExecution, JSON::ParserError
      nil
    end

    def asset_id
      @asset_id ||= GitHub.get_release(@owner, @repo, @tag)["assets"]
                          .find { |a| a["name"] == @filename }
                          .fetch("id") { raise CurlDownloadStrategyError, "Asset not found" }
    end
  end

  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "1c4b63584b097ebd4d05f460a7f38423a8e53550d95f4e31bf8717d8166f7ee0"
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v#{version}/cwf_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/convoyai/eng-dev-tooling/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "6858a8bbda7306cb4a82eb22db557025aea774663223b5bfd107dde391c2689a"
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v#{version}/cwf_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/convoyai/eng-dev-tooling/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  on_linux do
    on_intel do
      sha256 "e7f0e707114588af90d6e3fb454fb462f0bffcd5eb0219566fe0dc56b97494e9"
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v#{version}/cwf_#{version}_linux_amd64.tar.gz",
        verified: "github.com/convoyai/eng-dev-tooling/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "5810b20d6a27f1fa3f590d37db38fc3587caa794a02afbc0c20d20b70d124e14"
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v#{version}/cwf_#{version}_linux_arm64.tar.gz",
        verified: "github.com/convoyai/eng-dev-tooling/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "cwf"
  desc "Common Workflow tool: worktree/tmux session driver and turnkey sandboxing for the Common repos"
  homepage "https://github.com/convoyai/eng-dev-tooling"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "cwf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cwf"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    cwf needs a sibling checkout of the eng-dev-tooling "Tools Repo" (the repo this
    formula is built from — it contains the .cwf-tools-repo and sandcat/profiles/
    markers) to
    resolve sandbox profiles and templates at runtime. See the Usage/Prerequisites
    section of that repo's README.md (and docs/getting-started.md) for the
    sibling-checkout convention and the COMMON_DEV_TOOLS override.
  EOS
end
