# This file was generated by GoReleaser. DO NOT EDIT.
cask "cwf" do
  require "download_strategy"

  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      set_github_token
      meta[:headers] ||= []
      meta[:headers] << "Accept: application/octet-stream"
      meta[:headers] << "Authorization: Bearer #{@github_token}"
      ghurl = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
      super(ghurl, name, version, **meta)
    end

    def parse_url_pattern
      url_pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid url pattern" unless @url =~ url_pattern

      _, @owner, @repo, @tag, @filename = *@url.match(url_pattern)
    end

    def download_url
      "https://#{@github_token}@api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
    end

    private

    def set_github_token
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      @github_token = github_cli_token if @github_token.to_s.empty?
      raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required." if @github_token.to_s.empty?

      ENV["HOMEBREW_GITHUB_API_TOKEN"] = @github_token

      # validate access
      GitHub.repository(@owner, @repo)
    end

    def github_cli_token
      return unless which("gh") && which("jq")
      return unless system("gh", "auth", "status", out: File::NULL, err: File::NULL)

      username = Utils.safe_popen_read(
        "sh", "-c",
        "gh auth status --json hosts | jq -r '.hosts[\"github.com\"][].login'",
      ).strip
      return if username.empty? || username == "null" || username.include?("\n")

      token = Utils.safe_popen_read("gh", "auth", "token", "--user", username).strip
      token unless token.empty?
    rescue ErrorDuringExecution
      nil
    end

    def asset_id
      @asset_id ||= GitHub.get_release(@owner, @repo, @tag)["assets"]
                          .find { |a| a["name"] == @filename }
                          .fetch("id") { raise CurlDownloadStrategyError, "Asset not found" }
    end
  end

  version "0.2.5"

  on_macos do
    on_intel do
      sha256 "b3bfc04410bce5ffa79e8d38c25380c6e8419e06b1dcefc2eca1d377dcfd4561"
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v#{version}/cwf_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/convoyai/eng-dev-tooling/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "5a157e0f0a180f4485b8d7510a7f6d2d3562029ef05de590fc1fc0006570d5d5"
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v#{version}/cwf_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/convoyai/eng-dev-tooling/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  on_linux do
    on_intel do
      sha256 "6ed2f6a59fec9c95189de8a81a413b980b914a817d4d80568f49d82d5dbd4df7"
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v#{version}/cwf_#{version}_linux_amd64.tar.gz",
        verified: "github.com/convoyai/eng-dev-tooling/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "3b4d0421483bbe31c1b8b032884dc56b903e6f7984aadd7f82f373fb810cc73b"
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v#{version}/cwf_#{version}_linux_arm64.tar.gz",
        verified: "github.com/convoyai/eng-dev-tooling/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "cwf"
  desc "Common Workflow tool: worktree/tmux session driver and turnkey sandboxing for the Common repos"
  homepage "https://github.com/convoyai/eng-dev-tooling"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
      "tmux",
    ]

  binary "cwf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cwf"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    cwf needs a sibling checkout of the eng-dev-tooling "Tools Repo" (the repo this
    formula is built from — it contains the .cwf-tools-repo and sandcat/profiles/
    markers) to
    resolve sandbox profiles and templates at runtime. See the Usage/Prerequisites
    section of that repo's README.md (and docs/getting-started.md) for the
    sibling-checkout convention and the COMMON_DEV_TOOLS override.
  EOS
end
