# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "github_private_release_download_strategy"
class Cwf < Formula
  desc "Common Workflow tool: worktree/tmux session driver and turnkey sandboxing for the Common repos"
  homepage "https://github.com/convoyai/eng-dev-tooling"
  version "0.1.1"

  depends_on "git"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.1/cwf_0.1.1_darwin_amd64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "ce8acb97c1858c95ca1ffd310974153497e2c3606a74302ddb685d323c03df8d"

      define_method(:install) do
        bin.install "cwf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.1/cwf_0.1.1_darwin_arm64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "cfa57fe73cc938b0f0dd65911cbcec06060ff1780a223edeae16be4048a95bc5"

      define_method(:install) do
        bin.install "cwf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.1/cwf_0.1.1_linux_amd64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "5b4756e242c5d3f1c19dd8e0eb799a6755db0de80644ba3132a5a63a3cbabd9b"
      define_method(:install) do
        bin.install "cwf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.1/cwf_0.1.1_linux_arm64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "41d5a2a7ad85368bd7ca1e117a50a580258aa0544fae8e08025fa03f569606fb"
      define_method(:install) do
        bin.install "cwf"
      end
    end
  end

  def caveats
    <<~EOS
      cwf needs a sibling checkout of the eng-dev-tooling "Tools Repo" (the repo this
      formula is built from — it contains sandcat/profiles/ and the config schema) to
      resolve sandbox profiles and templates at runtime. See the Usage/Prerequisites
      section of that repo's README.md (and COMMON-TOOL-DESIGN.md §9) for the
      sibling-checkout convention and the COMMON_DEV_TOOLS override.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cwf version")
  end
end
