# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "github_private_release_download_strategy"
class Cwf < Formula
  desc "Common Workflow tool: worktree/tmux session driver and turnkey sandboxing for the Common repos"
  homepage "https://github.com/convoyai/eng-dev-tooling"
  version "0.1.3"

  depends_on "git"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.3/cwf_0.1.3_darwin_amd64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "dd9390808d38cd75db1bdd4665661c74a8807982b27d762c070fc012712a0617"

      define_method(:install) do
        bin.install "cwf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.3/cwf_0.1.3_darwin_arm64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "9917b9e85e98b35195e6ce2184ac2c47890cc334059114a23a5a93fd5555202b"

      define_method(:install) do
        bin.install "cwf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.3/cwf_0.1.3_linux_amd64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "88365bbf0f7a958ee2f6b93395bc7a0301c27ab6a8910535d54af13b2dbb75a4"
      define_method(:install) do
        bin.install "cwf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.3/cwf_0.1.3_linux_arm64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "e5a980ac7f261966d8c07ca7ddeb8b1cf607ef570b8bdc694d27a4a332d2eecf"
      define_method(:install) do
        bin.install "cwf"
      end
    end
  end

  def caveats
    <<~EOS
      cwf needs a sibling checkout of the eng-dev-tooling "Tools Repo" (the repo this
      formula is built from — it contains sandcat/profiles/ and the config schema) to
      resolve sandbox profiles and templates at runtime. See the Usage/Prerequisites
      section of that repo's README.md (and COMMON-TOOL-DESIGN.md §9) for the
      sibling-checkout convention and the COMMON_DEV_TOOLS override.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cwf version")
  end
end
