# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "github_private_release_download_strategy"
class Cwf < Formula
  desc "Common Workflow tool: worktree/tmux session driver and turnkey sandboxing for the Common repos"
  homepage "https://github.com/convoyai/eng-dev-tooling"
  version "0.1.2"

  depends_on "git"
  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.2/cwf_0.1.2_darwin_amd64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "cad27dd567dc7e31ed14a363b4a277ff2728e39e9e9e9163e2ef7ed5a33d528d"

      define_method(:install) do
        bin.install "cwf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.2/cwf_0.1.2_darwin_arm64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "4d15e9a91854affebc3aca920a1d2b1be9c6a921959b77ec87c5bf9d79bf233a"

      define_method(:install) do
        bin.install "cwf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.2/cwf_0.1.2_linux_amd64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "8e1fbfa03b36db368c6ca9c90779d018c6f8f03f88143b15079984d08e6da290"
      define_method(:install) do
        bin.install "cwf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/convoyai/eng-dev-tooling/releases/download/v0.1.2/cwf_0.1.2_linux_arm64.tar.gz", using: GitHubPrivateReleaseDownloadStrategy
      sha256 "dbf357498aae0bff459917d845d9221e222fe1574a209414b15a927dc94c2fde"
      define_method(:install) do
        bin.install "cwf"
      end
    end
  end

  def caveats
    <<~EOS
      cwf needs a sibling checkout of the eng-dev-tooling "Tools Repo" (the repo this
      formula is built from — it contains sandcat/profiles/ and the config schema) to
      resolve sandbox profiles and templates at runtime. See the Usage/Prerequisites
      section of that repo's README.md (and COMMON-TOOL-DESIGN.md §9) for the
      sibling-checkout convention and the COMMON_DEV_TOOLS override.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cwf version")
  end
end
